/** @type {import('tailwindcss').Config} */
// Tailwind config for SecureScope — matches the exact design token colors,
// font families, and border radii from the original HTML prototype.
export default {
  // Enable dark mode via the 'dark' class on <html>
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-surface-variant': '#c1c6d6',
        'surface-variant': '#31353c',
        'error': '#ffb4ab',
        'on-tertiary': '#522300',
        'on-primary-container': '#00285b',
        'surface-container-highest': '#31353c',
        'surface-container-high': '#262a31',
        'on-primary': '#002f68',
        'on-secondary': '#14305b',
        'on-tertiary-fixed': '#321300',
        'surface-dim': '#10141a',
        'surface-container-lowest': '#0a0e14',
        'on-primary-fixed': '#001a40',
        'tertiary-fixed': '#ffdbc8',
        'primary-container': '#498fff',
        'on-background': '#dfe2eb',
        'outline-variant': '#414754',
        'on-secondary-container': '#9db5e9',
        'on-primary-fixed-variant': '#004492',
        'primary-fixed-dim': '#acc7ff',
        'inverse-surface': '#dfe2eb',
        'secondary-fixed': '#d7e2ff',
        'on-error': '#690005',
        'surface-bright': '#353940',
        'secondary': '#aec7fb',
        'tertiary': '#ffb68b',
        'surface-tint': '#acc7ff',
        'secondary-fixed-dim': '#aec7fb',
        'error-container': '#93000a',
        'on-secondary-fixed': '#001a40',
        'inverse-primary': '#005bbf',
        'tertiary-fixed-dim': '#ffb68b',
        'on-error-container': '#ffdad6',
        'surface-container-low': '#181c22',
        'primary': '#acc7ff',
        'inverse-on-surface': '#2d3137',
        'tertiary-container': '#e47014',
        'on-tertiary-container': '#481e00',
        'on-surface': '#dfe2eb',
        'surface': '#10141a',
        'on-secondary-fixed-variant': '#2e4673',
        'secondary-container': '#2e4673',
        'primary-fixed': '#d7e2ff',
        'outline': '#8b909f',
        'on-tertiary-fixed-variant': '#753400',
        'background': '#10141a',
        'surface-container': '#1c2026',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
